---
title: "Untitled"
author: "Dumky de Wilde"
date: "2 July 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyr")
library("ggplot2")
library("RColorBrewer")

bg_and_axes <-  theme(
  panel.background = element_rect(fill = NA),
  panel.grid.major.y = element_line(colour = "#cccccc", size = 0.3, linetype = "dotted"),
  panel.grid.major.x = element_blank(),
  axis.ticks.y = element_blank(),
  axis.line.x = element_line(color = "black", size = 0.5),
  axis.text = element_text(colour = "#666666"),
  axis.title = element_text(colour = "#999999", face = "italic"),
  axis.text.x = element_text(margin = margin(16,0,12,0)),
  axis.text.y = element_text(margin = margin(0,16,0,12)),
  plot.title = element_text(family = "Avenir", size = rel(2), 
                            margin = margin(0,6,24,6), hjust = 0),
  plot.margin = unit(c(1,1,1,1), "cm"))
```

```{r}
data <- read.csv2("online_marketing_tools.csv")

tools_used <- data %>%
  count()

```

```{r}
p <- ggplot(data, aes())

```



```

